openapi: 3.1.0
info:
  title: Octo Deck API
  version: 1.0.0
tags: []
paths:
  /cards:
    get:
      operationId: getCards
      summary: カード一覧取得
      description: 自分のデッキを取得
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items:
                      $ref: '#/components/schemas/Card'
                required:
                  - cards
    post:
      operationId: addCardToDeck
      summary: カードをデッキに追加
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: '#/components/schemas/Card'
                required:
                  - card
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
  /cards/me:
    get:
      operationId: getMyCard
      summary: 自分のカード取得
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: '#/components/schemas/Card'
                required:
                  - card
  /cards/{githubId}:
    get:
      operationId: getCard
      summary: 指定したカード取得
      description: デッキにないカードも取得できる
      parameters:
        - name: githubId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: '#/components/schemas/Card'
                required:
                  - card
    delete:
      operationId: removeCardFromDeck
      summary: カードをデッキから削除
      parameters:
        - name: githubId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: '#/components/schemas/Card'
                required:
                  - card
  /communities:
    get:
      operationId: getCommunities
      summary: コミュニティ一覧取得
      description: 自分が入っているコミュニティ一覧取得
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  communities:
                    type: array
                    items:
                      $ref: '#/components/schemas/Community'
                required:
                  - communities
    post:
      operationId: createCommunity
      summary: コミュニティを作成
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  community:
                    $ref: '#/components/schemas/Community'
                required:
                  - community
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
  /communities/{id}:
    get:
      operationId: getCommunity
      summary: 指定したコミュニティ取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  community:
                    $ref: '#/components/schemas/Community'
                required:
                  - community
    delete:
      operationId: deleteCommunity
      summary: コミュニティを削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  community:
                    $ref: '#/components/schemas/Community'
                required:
                  - community
  /communities/{id}/cards:
    get:
      operationId: getCommunityCards
      summary: 指定したコミュニティのカード一覧取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items:
                      $ref: '#/components/schemas/Card'
                required:
                  - cards
    post:
      operationId: addCardToCommunity
      summary: 指定したコミュニティに自分のカードを追加
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: '#/components/schemas/Card'
                required:
                  - card
    delete:
      operationId: removeCardFromCommunity
      summary: 指定したコミュニティの自分のカードを削除
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: '#/components/schemas/Card'
                required:
                  - card
  /stats/me:
    get:
      operationId: getMyStats
      summary: 自分の統計情報取得
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  stats:
                    $ref: '#/components/schemas/UserStats'
                required:
                  - stats
  /stats/{githubId}:
    get:
      operationId: getUserStats
      summary: ユーザーの統計情報取得
      parameters:
        - name: githubId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  stats:
                    $ref: '#/components/schemas/UserStats'
                required:
                  - stats
security:
  - BearerAuth: []
components:
  schemas:
    Card:
      type: object
      required:
        - githubId
        - userName
        - fullName
        - iconUrl
        - identicon
      properties:
        githubId:
          type: string
        userName:
          type: string
        fullName:
          type: string
        iconUrl:
          type: string
        identicon:
          $ref: '#/components/schemas/Identicon'
    Community:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Contribution:
      type: object
      required:
        - date
        - count
      properties:
        date:
          type: string
          format: date
        count:
          type: integer
          format: int32
    Identicon:
      type: object
      required:
        - color
        - blocks
      properties:
        color:
          type: string
          description: 'カラーコード 例: #RRGGBB'
        blocks:
          type: array
          items:
            type: array
            items:
              type: boolean
          description: 5x5の二次元配列。trueがブロック
    UserStats:
      type: object
      required:
        - contributions
      properties:
        contributions:
          type: array
          items:
            $ref: '#/components/schemas/Contribution'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
servers:
  - url: http://localhost:8080
    description: Local
    variables: {}
  - url: https://dev.api.octo-deck.furari.co
    description: Development
    variables: {}
  - url: https://stg.api.octo-deck.furari.co
    description: Staging
    variables: {}
  - url: https://api.octo-deck.furari.co
    description: Production
    variables: {}
