name: CD

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-distribute-to-testflight:
    runs-on:
      - self-hosted
      - macOS
      - ARM64
      - tartelet
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        run: |
          xcodes select
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Setup Deploy Key for Match
        run: |
          echo '${{ secrets.MATCH_GIT_PRIVATE_KEY }}' > ~/.ssh/kantacky-apple-certificates-deploy-key.pem
          chmod 600 ~/.ssh/kantacky-apple-certificates-deploy-key.pem
          git config --global user.email "iam@kantacky.com"
      - name: Setup App Store Connect API Key
        run: |
          echo '${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}' > ./fastlane/app_store_connect_api_key.json
      - name: Setup Project
        run: task install
      - name: Build and Distribute to TestFlight
        run: bundle exec fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ~/.ssh/kantacky-apple-certificates-deploy-key.pem
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT_BASE64 }}
