name: CD

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-distribute-to-testflight:
    runs-on:
      - self-hosted
      - macOS
      - ARM64
      - tartelet
    timeout-minutes: 60
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.KANTACKY_APPLE_CERTIFICATES_APP_ID }}
          private-key: ${{ secrets.KANTACKY_APPLE_CERTIFICATES_PRIVATE_KEY }}
          owner: kantacky
          repositories: apple-certificates
      - name: Generate Git Basic Authorization for Match
        id: generate-git-basic-authorization
        run: |
          echo "authorization=$(echo -n "x-access-token:${{ steps.generate-token.outputs.token }}" | base64)" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        run: |
          xcodes select
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Setup App Store Connect API Key
        run: |
          echo '${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}' > ./fastlane/app_store_connect_api_key.json
      - name: Build and Distribute to TestFlight
        run: fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ steps.generate-git-basic-authorization.outputs.authorization }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT_BASE64 }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
